export const dashboard="/"
export const signin="/sign-in"
export const signup = "/sign-up"
export const logout="/logout"
export const profile = "/profile"
export const verifyAccount =  "/verify-account"
export const createPost = "/create-post"