const CREATE_POST_REQUEST = "CREATE_POST_REQUEST"
const CREATE_POST_FAIL = "CREATE_POST_FAIL"
const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS"

const EDIT_POST_REQUEST = "EDIT_POST_REQUEST"
const EDIT_POST_FAIL = "EDIT_POST_FAIL"
const EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS"

const DELETE_POST_REQUEST = "DELETE_POST_REQUEST"
const DELETE_POST_FAIL = "DELETE_POST_FAIL"
const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS"

const FETCH_POST_REQUEST = "FETCH_POST_REQUEST"
const FETCH_POST_FAIL = "FETCH_POST_FAIL"
const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS"





export default function userReducer(state={},action){
    switch(action.type){
        default: return state
    }
}